version: '3'

services:
  postgres:
    # Official Postgres image from DockerHub (we use the last version)
    image: postgres
    container_name: "database"
    restart: always

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "iamtheadmin12345"

  pgAdmin:
    image: dpage/pgadmin4
    container_name: "pgAdmin"
    restart: always
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin

  backend:
    build: .
    container_name: API
    depends_on:
      - postgres

    ports:
      - 3001:3001   # Currently not in use, hardcoded
